# permissions for end users to view kieapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kieapp-viewer-role
rules:
- apiGroups:
  - app.kiegroup.org
  resources:
  - kieapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.kiegroup.org
  resources:
  - kieapps/status
  verbs:
  - get
