
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - app.kiegroup.org
  resources:
  - kieapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.kiegroup.org
  resources:
  - kieapps/finalizers
  verbs:
  - update
- apiGroups:
  - app.kiegroup.org
  resources:
  - kieapps/status
  verbs:
  - get
  - patch
  - update
